"""Copies sold field

Revision ID: 28fd3cdc6c38
Revises: 
Create Date: 2021-03-17 14:57:32.186274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fd3cdc6c38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('copies_sold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'copies_sold')
    # ### end Alembic commands ###
